import { formValidators } from "../../../validators/formValidators";

export const registerFormPlayerInputs = [
  {
    tag: "Name",
    name: "name",
    type: "text",
    defaultValue: "",
    isRequired: true,
    validators: [formValidators.notEmptyValidator],
  },
  {
    tag: "Surname",
    name: "surname",
    type: "text",
    defaultValue: "",
    isRequired: true,
    validators: [formValidators.notEmptyValidator],
  },
  {
    tag: "Nickname",
    name: "nickname",
    type: "text",
    defaultValue: "",
    isRequired: true,
    validators: [formValidators.notEmptyValidator],
  },
  {
    tag: "Email",
    name: "email",
    type: "text",
    defaultValue: "",
    isRequired: true,
    validators: [formValidators.notEmptyValidator],
  },
  {
    tag: "Username",
    name: "username",
    type: "text",
    defaultValue: "",
    isRequired: true,
    validators: [formValidators.notEmptyValidator],
  },
  {
    tag: "Password",
    name: "password",
    type: "password",
    defaultValue: "",
    isRequired: true,
    validators: [formValidators.notEmptyValidator],
  },
  {
    tag: "Avatar",
    name: "avatar",
    type: "text",
    defaultValue: "",
    isRequired: true,
    validators: [formValidators.notEmptyValidator],
  },
  {
    tag: "Biography",
    name: "biography",
    type: "text",
    defaultValue: "",
    isRequired: false, 
    validators: [],
  },
  {
    tag: "Location",
    name: "location",
    type: "text",
    defaultValue: "",
    isRequired: true, 
    validators: [formValidators.notEmptyValidator],
  },
  {
    tag: "Birthdate",
    name: "birthdate",
    type: "date",
    defaultValue: "",
    isRequired: false, 
    validators: [],
  },
  {
    tag: "Favorite Genres",
    name: "favoriteGenres",
    type: "text",
    defaultValue: "",
    isRequired: false, 
    validators: [],
  },
  {
    tag: "Favorite Platforms",
    name: "favoritePlatforms",
    type: "text",
    defaultValue: "",
    isRequired: false, 
    validators: [],
  },
  {
    tag: "Favorite Sagas",
    name: "favoriteSagas",
    type: "text",
    defaultValue: "",
    isRequired: false, 
    validators: [],
  },
  {
    tag: "Profile Type",
    name: "profileType",
    type: "select", 
    values: ["CASUAL", "HARDCORE"],
    defaultValue: "CASUAL", 
    isRequired: true,
    validators: [formValidators.notEmptyValidator],
  }
];
